interface Dic {
    [key:number]: {color: string, text:string}
}

export const errorsDic:Dic= {
    6: {color: "info", text: "CFE en Carga"},
    7: {color: "info", text: "Gen en Carga"},
    8: {color: "danger", text: "Paro de Emergencia"},
    9: {color: "danger", text: "Apagado Sobre Aceleracion"},
    10: {color: "danger", text: "Apagado Falta Aceleracion"},
    11: {color: "danger", text: "Perdida de sella de velocidadx"},
    12: {color: "danger", text: "Apagado Sobre Frecuencia"},
    13: {color: "danger", text: "Apagado Falta Frecuencia"},
    14: {color: "danger", text: "Apagado Sobre Voltaje"},
    15: {color: "danger", text: "Apagado Falta Voltaje"},
    16: {color: "danger", text: "Apagado Sobre Carga"},
    17: {color: "danger", text: "Falla de Marcha"},
    18: {color: "danger", text: "Apagado Temperatura Alta"},
    19: {color: "danger", text: "Apagado Baja Pression de Aceite"},
    20: {color: "secondary", text: "Perdida de Frecuencia"},
    21: {color: "danger", text: "Apagado por Input"},
    22: {color: "danger", text: "Apagado Bajo Nivel de Combustible"},
    23: {color: "danger", text: "Apagado Bajo Nivel de Anticongelante"},
    24: {color: "warning", text: "Alarma Alta Temperatura"},
    25: {color: "warning", text: "Alarma Baja Pression de Aceite"},
    26: {color: "warning", text: "Alarma Sobre Carga"},
    27: {color: "warning", text: "Alarma Falla de Paro"},
    28: {color: "warning", text: "Alarma Bajo Niver de Aceite"},
    29: {color: "warning", text: "Alarma Falla de Carga"},
    30: {color: "warning", text: "Alarma Batteria Bajo Voltaje"},
    31: {color: "warning", text: "Alarma Batteria Sobre Voltaje"},
    32: {color: "warning", text: "Alarma Input"},
    33: {color: "warning", text: "Alarma Perdida de Senal de Aceleracion"},
    34: {color: "warning", text: "Alarma Bajo Nivel de Anticongelante"},
    35: {color: "warning", text: "Alarma Sensor de Temp con Falla"},
    36: {color: "warning", text: "Alarma Sensor de Pression con Falla"},
    37: {color: "warning", text: "Alarma Mantenimiento Pendiente"},
    38: {color: "warning", text: "Alarma Cargador Fallo"},
    39: {color: "warning", text: "Alarma Sobre Poder"},
    44: {color: "danger", text: "Apagado Sensor Temperatura Falla"},
    45: {color: "danger", text: "Apagado Sensor Pression Falla"},
    46: {color: "danger", text: "Apagado Falta de Mantenimiento"},
    47: {color: "danger", text: "Apagado Sobre Poder"},
}   